### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#1]
The first page when I opened my grain was 404 Page Not Found. There is no way to see files uploaded to it. And once I go to "Clients", any attempt to click on "Files" just fails. But I did manage to authenticate my ownCloud client to it, and I think it uploaded. I just can't see the files.

**Comment by mnutt** [comment]
Thanks for trying it out! I'm going to be packaging a slightly more complete release today, but could you let me know how you're running it? (from source or from the spk, and if from the spk what version?)

**Comment by ocdtrekkie** [comment]
0.10.3 spk

**Comment by mnutt** [comment]
Would you mind checking out https://github.com/mnutt/davros/releases/tag/v0.10.4?

And if you still get the 404, can you let me know if there's anything in the grain log?

**Comment by ocdtrekkie** [comment]
Still getting the 404 with both upgraded and new grains on 0.10.4. Grain log contains nothing interesting. However, the Java Console may be more helpful:

Error while processing route: home The operation is insecure. e.default<.socketFor@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/davros-bced84ea6776cf3b0f8213c3a2866ad4.js:2:2223
e.default<.init@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/davros-bced84ea6776cf3b0f8213c3a2866ad4.js:1:26503
r@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:11:18191
x/d@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:15:4852
O.create@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:15:7338
d@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:19822
o@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:18252
a.prototype.lookup@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:20297
I<._getHandlerFunction/<@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:13:6009
e.default<.applyToHandlers@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:19:28527
e.default<.applyToState@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:19:28224
l.prototype.applyIntent@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:19:26573
A@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:12:31929
I<._hydrateUnsuppliedQueryParams@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:13:7855
I<._prepareQueryParams@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:13:7371
I<._doTransition@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:13:7210
I<.transitionTo@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:13:4231
S<.transitionTo@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:12:26237
e.default<.beforeModel@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/davros-bced84ea6776cf3b0f8213c3a2866ad4.js:1:27308
r@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:11:18220
p@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:20:5065
n.prototype.runSharedModelHook@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:19:16348
n.prototype.runBeforeModelHook@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:19:15928
a/<@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:20:3764
y@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:20:8741
b@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:20:8836
g@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:20:8644
@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:14:6355
r.prototype.invoke@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:15391
r.prototype.flush@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:15925
n.prototype.flush@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:13952
a.prototype.end@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:8622
a.prototype.run@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:9140
a.prototype.join@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:5:9444
u.join@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:11:4734
u.bind/<@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:11:4940
ie.Callbacks/c@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:3:11394
ie.Callbacks/d.fireWith@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:3:12216
.ready@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:3:14073
s@https://alpha-864722a75024856586e86e618ecd5206.sandstorm.io/assets/vendor-65fb3868cda15e0d0224047f8809cb47.js:2:6611

**Comment by mnutt** [comment]
Ah, I notice that you're using https. I'll try testing on https and see if I can figure out what's going on.

**Comment by ocdtrekkie** [comment]
Yeah, between the managed servers being https, and Sandcats now offering https, that's gonna end up being a must. :D

**Comment by mnutt** [comment]
Alright, it looks like I wasn't ensuring that websockets used `wss:` and that was causing the error. I cut a new release that fixes it: https://github.com/mnutt/davros/releases/tag/v0.10.5

**Comment by ocdtrekkie** [comment]
You got it. Thanks!
