### ISSUE TITLE
Clients data missing

### ISSUE THREAD

**Issue by 0bpm** [mnutt/davros#105]
I'm still new to Sandstorm, so maybe I'm just missing something obvious, but when I open the Clients tab, all the text fields are empty. There's no server name, user or password I'd need to connect a WebDAV client.
The debug log doesn't show any errors either.

**Comment by ocdtrekkie** [comment]
Is there any chance you're opening the Davros frame in a new tab outside of the Sandstorm UI, perhaps? I definitely see that behavior when Davros is accessed outside of Sandstorm, but in Sandstorm it looks fine to me.

Can you also check your browser's dev console for errors?

**Comment by 0bpm** [comment]
Ahh, the web console showed the error. I had my nginx configured with `X-Frame-Options: “DENY”`.
Replacing that with a suitable Content-Security-Policy header fixed the issue.

**Comment by ocdtrekkie** [comment]
Glad to hear you got it resolved!
