### ISSUE TITLE
Checkboxes in 0.27.0/0.27.1 are weird

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#113]
I am excited about moving away from Material, but this seems to be a bit of a half-step here:

![image](https://user-images.githubusercontent.com/4399499/90315969-31a51180-dee5-11ea-8f47-8613dc1520de.png)
![image](https://user-images.githubusercontent.com/4399499/90315973-38cc1f80-dee5-11ea-9686-6a64fbf038b6.png)

Appears on both the Clients and Publish tabs.

**Comment by mnutt** [comment]
Is this still happening as of 0.28?

**Comment by ocdtrekkie** [comment]
Nope, you fixed this already.
