### ISSUE TITLE
OwnCloud iOS app + Davros on self-hosted Sandstorm

### ISSUE THREAD

**Issue by pdehaye** [mnutt/davros#12]
Is this supposed to work? If so, how? I get a "Can not authenticate against this server" error.

**Comment by ocdtrekkie** [comment]
From my understanding, there's some fixes needed in the mobile clients to work with Davros.

**Comment by pdehaye** [comment]
User @engelgabriel just gave me access to the beta of an owncloud iOS client supporting custom servers. The announcement is here: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/26 . FWIW it didn't work with my own Sandstorm install.

**Comment by ocdtrekkie** [comment]
Note that @mnutt has an open PR on the iOS client: https://github.com/owncloud/ios/pull/515

**Comment by mnutt** [comment]
@pdehaye: I can look into doing a custom iOS build and giving you access, I've never used TestFlight before though.

**Comment by engelgabriel** [comment]
Hi, are you guys talking about our Rocket.Chat app? We need to update the SPK with the latest build to get it to be compatible with the new mobile apps. We are working on that today.

**Comment by ocdtrekkie** [comment]
Not AFAIK, we are discussing Davros, which uses ownCloud's mobile apps.

**Comment by engelgabriel** [comment]
OK, so I am trying to understand why I was mentioned here... ideas?

**Comment by ocdtrekkie** [comment]
I don't know @engelgabriel Maybe he thought because the Rocket.Chat app doesn't work with his server, nor does the ownCloud client, that it's a general issue with his Sandstorm server?

But AFAIK, currently, the ownCloud iOS client doesn't work with Davros, but a pull request has been submitted to fix it.

**Comment by pdehaye** [comment]
Wow, way for me to get my wires crossed up and confuse everyone in the process! Davros/OwnCloud has nothing to do indeed with RocketChat, except that I was trying to see for both if the iOS app would work with my own Sandstorm install. 

Sorry for this, @engelgabriel, please ignore this thread . I will edit my comment above mentioning you and file separately for RocketChat, like I should have done from the start.

And @ocdtrekkie and @mnutt , I hear that you are working on it/aware of work going on on it, and would be glad to test/use when you are ready.

**Comment by JamborJan** [comment]
How is the status about compatibility with the iOS ownCloud client? Is there any bigger issue? Anything I can help with?

**Comment by mnutt** [comment]
We're closing in on it. The owncloud/ios pull request is still open and now being reviewed, there is just one more issue in the implementation to be worked out. There is a PR open for owncloud/android, as well.

**Comment by JamborJan** [comment]
Awesome, thanks for the great work @mnutt

**Comment by JamborJan** [comment]
Just in case there are more people waiting for this to be closed: the PR has been accepted on Feb. 2nd (3 days ago): https://github.com/owncloud/ios/pull/569

Now we only have to wait until OwnCloud publishes a new version of the client.

**Comment by mnutt** [comment]
@JamborJan unfortunately they took my PR, rewrote it into something that doesn't actually work, and merged _that_. I haven't yet deduced why it doesn't work, but they don't seem interested in anything more. The whole experience was a bit weird; but unfortunately I don't think OwnCloud iOS / OwnCloud Android will be interoperable.

**Comment by JamborJan** [comment]
That is not good. Any ideas how this can be solved? E.g. using another client? As far as I understood Davros is not build on ownCloud, only the sync to desktops is compatible. Right? What would a suitable mobile sync client need?

**Comment by mnutt** [comment]
Yeah, it's unfortunate. I'm curious what your use case for the mobile client is, to see if we can solve it another way. Is it mainly about a more performant/mobile-friendly interface to view files? Or for syncing files for offline use, or something else?

**Comment by JamborJan** [comment]
There is actual one use case I really miss now: I had set up a auto photo sync with Bit Torrent Sync before. On my Mac I have an Automator script waiting for incoming pictures taken with my mobile's camera  and starting an OCR process which makes PDFs out of it and filing them with a decent naming. Pretty good thing for book keeping or the paperless office.

Other less important use cases are that I have some files which I need to have on the go e.g. password saves and so on.

**Comment by ocdtrekkie** [comment]
Auto photo sync from the ownCloud client was super awesome. I'd be really
tempted to use it again if it went to a Davros grain.

-Jake Weisz

**Comment by mnutt** [comment]
This works in v0.16! Thanks to the sandstorm team!
