### ISSUE TITLE
Upload not working in 0.14.0

### ISSUE THREAD

**Issue by njuergens** [mnutt/davros#13]
Hey,

when I press the ''Upload" Button nothing happens. Tested on our own sandbox and in your demo server.

My JavaScript console says:
Error: Nothing handled the action 'nothing'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.

I'm using Firefox 41.0 on Ubuntu 14.04 AMD64.
Also tested Google Chrome Version 46.0.2490.80 (64-bit)

Thanks!
Nils Jürgens

**Comment by mnutt** [comment]
Sorry for that oversight! I've submitted v0.14.1, it'll hopefully be up in the next few days.

**Comment by njuergens** [comment]
Thanks for the quick update! Looking forward to more testing :-)

**Comment by mnutt** [comment]
v0.14.1 has been released, can you check to see if it's working for you now?

**Comment by njuergens** [comment]
The upload button works, thanks!
