### ISSUE TITLE
JS error on sandstorm / davros / web

### ISSUE THREAD

**Issue by jps-gdd** [mnutt/davros#130]
Got an issue with davros folder containing psd, eps, and jpg files.
When i try to open this folder (with Chrome), got an error:
```
Uncaught (in promise) TypeError: Cannot read property '0' of null
    at e.get width [as width] (davros-e9e7b3721208f8a0aac7a0c92502b356.js:195)
    at davros-e9e7b3721208f8a0aac7a0c92502b356.js:26
    at Array.map (<anonymous>)
    at u.get directoryGalleryItems [as directoryGalleryItems] (davros-e9e7b3721208f8a0aac7a0c92502b356.js:26)
    at Be._e [as getPath] (vendor-bbf79c67bc6f6f74fa4275b207c361d8.js:1126)
    at vendor-bbf79c67bc6f6f74fa4275b207c361d8.js:2616
    at e.track (vendor-bbf79c67bc6f6f74fa4275b207c361d8.js:3205)
    at a.value (vendor-bbf79c67bc6f6f74fa4275b207c361d8.js:2616)
    at zt.value (vendor-bbf79c67bc6f6f74fa4275b207c361d8.js:3002)
    at Ae (vendor-bbf79c67bc6f6f74fa4275b207c361d8.js:667)
```

Have other grains with JPG, no trouble.

When i delete jpg extension, no more JS error
![image](https://user-images.githubusercontent.com/72876185/126788246-64303bc3-fa30-4b95-9eca-0f00b67ebc19.png)

Have the exact same problem on another folder of this grain, only jpg files inside, but filename is 30 / 40 chars long.

Don't know if this problem occurs for other people ?

**Comment by jps-gdd** [comment]
Logs:
```
PROPFIND /remote.php/webdav/ 207 63.165 ms - -
PROPFIND /remote.php/webdav/Logos/ 207 38.965 ms - -
PROPFIND /remote.php/webdav/Logos/JPG%20CMJN/ 207 19.855 ms - -
```

**Comment by ocdtrekkie** [comment]
Yeah, we're talking about trying to have someone go in and work on some of these weird edge cases Davros has with file handling.

**Comment by mnutt** [comment]
Thanks for reporting, fixed in https://github.com/mnutt/davros/commit/1e2ed8e2688778e9f5e613e0cb021cad27ed6a92.

**Comment by mnutt** [comment]
(will go out in Davros v0.29.0, soon-ish...)

**Comment by jps-gdd** [comment]
Davros is up to date in 0.31.1 (in sandstorm), but js file was not flush and does not contains corrected datas (https://github.com/mnutt/davros/commit/1e2ed8e2688778e9f5e613e0cb021cad27ed6a92)

Anything to do ?
