### ISSUE TITLE
Enable web publishing switch doesn't change

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#134]
In 0.31.0, the checked state/slid right state doesn't appear when you enable web publishing:

![image](https://user-images.githubusercontent.com/4399499/134236060-86269e2d-8095-4a3e-b9ec-78cfc2d47d8c.png)

The same issue occurs with the same UI element in "put auth in URL" on the client tab.

**Comment by mnutt** [comment]
I noticed these, but didn't get a chance to address them and will do that shortly. The button works, but gives no indication that it worked.

**Comment by ocdtrekkie** [comment]
Fixed in 0.31.1.
