### ISSUE TITLE
Delete button freezes up grain

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#135]
In 0.31.0, tried opening the image and using the delete button inside, did this weird confusing UI and I couldn't get out of it without reloading the grain. (The little X doesn't work at all here.) Deleting from the new checked file list works fine.

![image](https://user-images.githubusercontent.com/4399499/134236460-4c8f8451-0f6e-460e-ad6a-c19cbd74db81.png)

**Comment by ocdtrekkie** [comment]
I assume what's happening here, is that the delete function now expects some sort of file selection, and since it's missing in this case, the element fails. As a note, I think it'd be nice to have the Move and Rename functions available from the preview view as well as fixing this one.

**Comment by mnutt** [comment]
Oh that's something I missed, and a straightforward fix. I can push up 0.31.1 fixing that tonight.

**Comment by ocdtrekkie** [comment]
Fixed by 0.31.1.
