### ISSUE TITLE
Curios questions

### ISSUE THREAD

**Issue by omsenjalia** [mnutt/davros#141]
1. Does it take your computer/mobile's Storage where you host the cloud storage (kinda stupid question but ye)
2. If yes then where example /davros/####/MyName/MyFoldersComeHere/FileComtentsHere

**will edit this if needed**

**Comment by ocdtrekkie** [comment]
Davros stores your files on whatever server you are running Sandstorm on. Sandstorm generally stores grain data at like /opt/sandstorm/var/grains/(grainId)/ or something somewhat similar.
