### ISSUE TITLE
Files uploaded via web UI do not appear in files list immediately

### ISSUE THREAD

**Issue by sprin** [mnutt/davros#21]
After uploaded a file via the web UI, the file does not appear in the files list immediately. The page must be refreshed.

Environment: Sandstorm Oasis, Firefox 42, Fedora 23

Steps to reproduce:
 - Select Upload from the web UI menu
 - Select a file from the file browser, click "open"

When the upload finishes, the file list does not show the new file, but it will appear on refresh. Server returns a 200 "ok" response after upload. The console shows a syntax parsing ember-cli-live-reload.js:

It looks like the request for ember-cli-live-reload.js is actually returning HTML:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Davros</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/" />
<meta name="davros/config/environment" content="%7B%22modulePrefix%22%3A%22davros%22%2C%22environment%22%3A%22development%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22contentSecurityPolicy%22%3A%7B%22default-src%22%3A%22%27none%27%22%2C%22script-src%22%3A%22%27self%27%22%2C%22font-src%22%3A%22%27self%27%22%2C%22connect-src%22%3A%22%27self%27%22%2C%22img-src%22%3A%22%27self%27%20data%3A%22%2C%22media-src%22%3A%22%27self%27%22%2C%22style-src%22%3A%22%27self%27%22%7D%2C%22APP%22%3A%7B%22name%22%3A%22davros%22%2C%22version%22%3A%220.0.0+03670927%22%7D%2C%22contentSecurityPolicyHeader%22%3A%22Content-Security-Policy-Report-Only%22%2C%22exportApplicationGlobal%22%3Atrue%7D" />
<script src="/ember-cli-live-reload.js" type="text/javascript"></script>
<div id='paper-wormhole'></div>

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/davros.css">

    
  </head>
  <body>
    

    <script src="assets/vendor.js"></script>
    <script src="assets/davros.js"></script>

    
  </body>
</html>
```

**Comment by mnutt** [comment]
Oh, that looks like a packaging mistake on my part. ember-cli-live-reload.js should only be enabled in development mode and should never have made it into production. In fact, I see "environment: development" in the config here. I'll make a new point release that fixes it.

**Comment by ocdtrekkie** [comment]
Could this be #19 as well? Everything seemed to 'work', but didn't update or display.

**Comment by mnutt** [comment]
It's extremely likely. I'll push out a new version and test it with Edge as well.

**Comment by mnutt** [comment]
Ok, I submitted v0.14.2 to the marketplace. If you'd like to test it ahead of then, you can do so here: https://mnutt.sandcats.io/shared/hNttoEKpQeWvGUCRmybPMReK9At3QjgZlOqpr54CIjd

**Comment by sprin** [comment]
Just started a new grain from the marketplace, and it's fixed. Thanks!
