### ISSUE TITLE
Unable to connect Windows ownCloud client to Oasis Sandstorm grain

### ISSUE THREAD

**Issue by koenigchristoph** [mnutt/davros#26]
Hi, 

I try to connect the ownCloud client on Win 7 64 bit to a Davros grain hosted on Oasis Sandstorm. After entering the credentials that Davros offers at the /clients tab the ownCloud client replies with "Connection closed".

This does not seem to be #12 which is limited to iOS.

Any Idea what I can do to narrow that down?

**Comment by JamborJan** [comment]
I don't have a solution here but want to add, that I have the same with the Mac OwnCloud client once in a while. For me it is as follows:
- The sync client has trouble with a file (not sure why or what kind of trouble)
- In the sync clients log I see two type entries, sometimes "connection closed" and sometimes "operation aborted" (not sure if this is the exact english translation as I use the German translated client)
- in this situation the file is obviously missing on the client
- after some minutes when the client tries again to get this file it is working, no errors

For me that happened once in a while when I initially synced several devices. Not sure if there is an issue when there are too many requests.

If one of the developers needs further logs or something which needs to be tested let me know.

**Comment by koenigchristoph** [comment]
I have this when I initially try to sync the ownCloud client to the sandstorm davros. Where can I find the logs of the client? I do not see any in the Program dir.

**Comment by mnutt** [comment]
I have heard of this happening from someone else too but haven't been able to track down whether the error happens in Sandstorm or Davros. Any davros errors _should_ be logged to the console, except possibly if the app runs out of memory and crashes hard. I may try some stress testing over the weekend to see if I can replicate in a controlled environment.

**Comment by JamborJan** [comment]
@mnutt I will check all my log files from Davros if I find something.

@koenigchristoph there is a log in the client UI should be the same UI on windows (I guess). 

![bildschirmfoto_2016-02-05_um_17_52_48](https://cloud.githubusercontent.com/assets/7508960/12852849/5ca67f16-cc31-11e5-8c05-40225d286f00.png)

I found also a way of starting a special debug version of the client:

## Windows
Get to "Start > Programs > Owncloud" and right-click on owncloud icon.
Select "Send To > Desktop (Create Shortcut".
Right click on the newly appearing owncloud icon on desktop and select "Properties".
Select "Target" value in appearing dialog and append following text
```
 --logwindow
```
Now start owncloud by double clicking new desktop icon

## Linux
Open "Terminal" and type following command, press Enter:
```
owncloud --logwindow
```

## Mac OS X
Open "Terminal" and type following command:
```
/Applications/owncloud.app/Contents/MacOS/owncloud --logwindow
```
## Log File
In addition, you can tell the desktop client to output the log to a file. For that, add the --logfile option to the command/shortcut you use to run the client, for example:
```
owncloud --logfile <logfilepathandname>
```

Source: https://forum.owncloud.org/viewtopic.php?f=17&t=6526

**Comment by koenigchristoph** [comment]
Thanks @JamborJan for the description, With this I managed to get a log. Here it is. Hope it tells you something.
[owncloud.txt](https://github.com/mnutt/davros/files/121881/owncloud.txt)

**Comment by mnutt** [comment]
@koenigchristoph can you try with v0.16? I believe the new Sandstorm update may have fixed this as well.

**Comment by JamborJan** [comment]
Awesome! Works for me.

**Comment by koenigchristoph** [comment]
Hi Michael,

I still have the same problem. I created a new grain and still have:

* The “Files” tab says “404 Not Found We couldn't find this page. Please check the URL to make sure it is correct.” (only in Chrome. This seems to be an unrelated bug)
* The OwnCloud client tells be “connection closed” after I enter username and password.

I you give me an email address, I can send you an invite to the grain and you can see for yourself.



Von: Michael Nutt [mailto:notifications@github.com]
Gesendet: Mittwoch, 2. März 2016 01:07
An: mnutt/davros
Cc: Koenig, Dr.Christoph Jan
Betreff: Re: [davros] Unable to connect Windows ownCloud client to Oasis Sandstorm grain (#26)


@koenigchristoph<https://github.com/koenigchristoph> can you try with v0.16? I believe the new Sandstorm update may have fixed this as well.

**Comment by koenigchristoph** [comment]
Michael,

I just updated Davros to 1.16.1 on oasis and it works like a charm!

* no "file not found" message anymore
* ownCloud client connects perfectly on Win7

Thanks a lot!
