### ISSUE TITLE
Fork Idea: Synchronized Text/Markdown Files

### ISSUE THREAD

**Issue by simonv3** [mnutt/davros#29]
So I realize this is outside of the scope of Davros, but I've been pining for a really simple markdown editor that lets me edit from a folder on my computer and then backs it all up (Davros), but then ideally I could edit those files from within Sandstorm as well.

I suspect this is outside of the scope of Davros, but it would be cool to take the functionality that Davros supplies through a fork and focus it on something like this.

Thoughts?

Stretchgoals: Jekyll publishing to github, or something similar.

**Comment by mnutt** [comment]
I'd be totally fine with a fork, but I also think this functionality might fit in well with the upcoming Powerbox feature in Sandstorm. Ideally for any file type, davros could ask sandstorm "do you have any apps installed that support markdown?" and then seamlessly send you into that app to edit.

(I've also thought about having frontend plugins for things like document editing, photo galleries, music playlists, etc but hopefully powerbox will be a more scalable solution)

**Comment by simonv3** [comment]
I didn't realize Powerbox was a thing / in the works but it sounds like it would indeed be a good / much easier to implement solution for this. I'll wait to see what that will be.
