### ISSUE TITLE
Started new Davros grain - generated share link - share link throws a 404

### ISSUE THREAD

**Issue by grantpotter** [mnutt/davros#30]
As seen at:
https://oet.sandcats.io/shared/AKnXO4V0nQ-2RiX-kucsCQkFFZ6sIYAmmj5SAxqxbWq

There are a couple photos and a .MD file in there

**Comment by paulproteus** [comment]
FWIW this was discussed on #sandstorm IRC

link: https://botbot.me/freenode/sandstorm/2016-02-04/?msg=59400628&page=4

**Comment by mnutt** [comment]
I believe this is fixed in v0.15.3. (sorry for the late notification!)
