### ISSUE TITLE
IE11: 404 Not Found at root

### ISSUE THREAD

**Issue by kentonv** [mnutt/davros#32]
Below is a fresh Davros grain running on IE11. If I share the grain, it works correctly in other browsers.

![screenshot from 2016-02-22 17-54-43](https://cloud.githubusercontent.com/assets/4001805/13239229/6f4ea0e4-d98d-11e5-9efc-ee70f5d61c17.png)

**Comment by mnutt** [comment]
Fixed via https://github.com/mnutt/davros/commit/37630d6ce8681206a6ca2276f1ea2e6818e2a87f in v0.16.1.
