### ISSUE TITLE
Long uploads get interrupted frequently

### ISSUE THREAD

**Issue by mrdomino** [mnutt/davros#38]
I'm trying to upload about 30GB to a Davros share, and it seems as though the grain is getting shut down at regular intervals, possibly because the keepalive is expiring.

**Comment by paulproteus** [comment]
Question about uploads: Are you doing them by the web browser, or by a
mobile/native/desktop/CLI client?

**Comment by mrdomino** [comment]
It's with the Owncloud desktop client on Linux.

**Comment by paulproteus** [comment]
It could also be being oom-killed due to a known Sandstorm http-bridge bug.
Steve, any chance that's what's going on? dmesg and/or syslog will mention
OOM kill events, fwiw.

**Comment by mrdomino** [comment]
Seems unlikely -- the profile is lots of smallish files, and the server has
a decent amount of RAM. Haven't looked at anything other than the grain
logs yet though -- if I get a chance, I'll try and reproduce it and take a
look.

**Comment by mnutt** [comment]
I've run into this same issue as well. The owncloud client had an issue involving mtimes and an off-by-one error, I've updated Davros's mtime handling to account for this. Would you mind trying again, and if it's still an issue I'll re-open.
