### ISSUE TITLE
Sync with unison (feature request)

### ISSUE THREAD

**Issue by garrison** [mnutt/davros#39]
Might it be possible to allow one to sync with a Davros repository using the [Unison](https://www.cis.upenn.edu/~bcpierce/unison/) file synchronization tool?  This would allow intelligent offline support, able to propagate changes in both directions and resilient to failure.

Personally, I have been very happy/impressed with Unison in the past and am now looking to move to Davros or another Sandstorm app for each of my file collections, instead of having them all on a server I can access over unison via ssh.  Intelligent offline support is very important to me, so I am hesitant to move away from Unison and adopt something else entirely.  But if there exist offline WebDAV tools that are just as intelligent as unison, knowing of them may negate the need for this feature.

**Comment by paulproteus** [comment]
FWIW, I've been theoretically interested in seeing git-annex get documented
against Davros for a similar reason.

**Comment by mnutt** [comment]
I have been using it with git-annex and it works great. My only wish is that git-annex gave enough info for its special remotes to show an actual web UI. As is, it works, but the web UI isn't very useful.

**Comment by avatar1024** [comment]
I personally use syncthing to sync my Davros folders on my local machine and that seems to work great.

**Comment by garrison** [comment]
BTW, while I love unison I am beginning to realize this may be infeasible.  If the versions of unison on each end [are different](https://alliance.seas.upenn.edu/~bcpierce/wiki/index.php?n=Main.UnisonFAQTroubleshooting), or (!) even [if the versions of Ocaml that unison was compiled with](https://github.com/bcpierce00/unison/issues/15) differ, the sync may fail.  I have no idea how you would begin to support all versions of unison in the wild within a sandstorm package.

**Comment by garrison** [comment]
Closing this, as I think there is no reasonable path forward given my previous comment.
