### ISSUE TITLE
.jsdav file visible in folder

### ISSUE THREAD

**Issue by zarvox** [mnutt/davros#4]
While syncing is in progress between owncloud-client and Davros, I see this .jsdav file, which I probably shouldn't:

![screenshot1](https://cloud.githubusercontent.com/assets/307325/10898251/77f370e8-817d-11e5-95a2-837270025f3c.png)

**Comment by mnutt** [comment]
I'm thinking https://github.com/mnutt/davros/commit/9398fdbef1f44fb94dd39577fd8f3877aff1ea75 fixes it, I'll cut another release later tonight.

**Comment by zarvox** [comment]
Since you asked on IRC: the contents of that `.jsdav` file are: 

`{"framadate-0.spk":{"{DAV:}lastmodified":"1442564003"}}`

**Comment by mnutt** [comment]
Should be fixed now, please reopen if it isn't.
