### ISSUE TITLE
uploading images on mobile causes images to glitch

### ISSUE THREAD

**Issue by jadeqwang** [mnutt/davros#40]
Uploading images on mobile (whether through ownCloud mobile auto-upload from the camera or through selecting files to uplaod in the ownCloud mobile client) causes images to be glitched/scrambled. Here's a glitched image on Oasis:

![image](https://cloud.githubusercontent.com/assets/1584904/14240318/bc4a8620-f9f8-11e5-8d9c-49e9d7911334.png)

And also when synced to desktop:

![image](https://cloud.githubusercontent.com/assets/1584904/14240307/a4c6c342-f9f8-11e5-944b-9b57f5b480ae.png)

**Comment by gkoz** [comment]
Possibly related https://github.com/owncloud/android/issues/91

**Comment by gkoz** [comment]
Now that I know that the url for generic clients ends with `/remote.php/webdav` it turns out that while
the owncloud client on my Galaxy S3 used to corrupt almost every photo it uploads, FolderSync seems to upload them without a glitch and faster too.

**Comment by ocdtrekkie** [comment]
I experience this as well. I figured it was probably the client's fault though. owncloud/android#91 seems likely.

**Comment by ocdtrekkie** [comment]
oC client 2.0 has some error checking and retry capability for uploads. I don't know if it does any validation to see if the image was CORRECTLY uploaded, but this sounds promising: https://owncloud.org/blog/owncloud-android-client-2-0-comes-with-upload-view-federated-sharing-and-more/

**Comment by mnutt** [comment]
Everything in the Owncloud community is a bit in flux right now, but I'd try the Nextcloud client (free!) or possibly Cirrus (also free) https://play.google.com/store/apps/details?id=com.synox.android&hl=en

I believe this is a bug in the old Android Owncloud client but let me know if it is reproducible in newer clients and I'll re-open.

**Comment by alex-soderqvist** [comment]
I have tried a handful clients for android: cottoncloud, nextcloud, cirrus etc. None of the new ones are able to sign in with. Using older versions you are able to sign in and upload images, but images get glitched as in the example above. Also when you signed in you can update the app, so I did test this with both latest version of Nextcloud and Cottoncloud, latest version available in playstore as of today. The login persist and you are able to upload images, however they are still glitched. Does anyone know of any android client of any version working properly? Right know its not usable at all as backup for my mobile photos. Let me know if I can help test, send logs or whatever. I would really enjoy having this working propetly.
