### ISSUE TITLE
Sidebar text alignment differs on firefox

### ISSUE THREAD

**Issue by kentonv** [mnutt/davros#43]
Somehow the labels are aligned right instead of left.

![screenshot from 2016-04-08 12-58-21](https://cloud.githubusercontent.com/assets/4001805/14396079/55c0a462-fd8a-11e5-8ce5-66b374c7de41.png)

**Comment by mnutt** [comment]
I saw that before but forgot to open an issue about it, thanks for reminding me.

**Comment by mnutt** [comment]
This is fixed now, in one of the updates I pushed last week.
