### ISSUE TITLE
Javascript errors running in vagrant-spk dev

### ISSUE THREAD

**Issue by timbertson** [mnutt/davros#47]
Aside from a few teething problems setting up the development environment (#46), I'm getting console errors now that the davros UI is running:

![screenshot from 2016-04-28 21-24-14](https://cloud.githubusercontent.com/assets/14172/14884620/6bd68316-0d89-11e6-9680-35604c71c1ff.png)

(the UI itself is just a blank screen)

Any ideas?

**Comment by timbertson** [comment]
I worked around the jquery issue by pinning jquery to `1.11.3` (a better solution would be upgrading ember, since this is fixed in https://github.com/emberjs/ember.js/pull/12793 - but that sounds like more work ;))

Now I'm getting:

    vendor.js:180 Uncaught Error: Could not find module `ember/load-initializers` imported from `davros/app`

`ember-load-initializers` version 0.1.7 was installed by bower and resides in `bower_components`. The module definition doesn't appear in assets/vendor.js after an ember build though.

**Comment by mnutt** [comment]
It looks like some dependencies I didn't have pinned ended up being upgraded and breaking things. I went ahead and upgraded the app to ember 2.5, hopefully it should fix the errors you're seeing. (you may need to remove `bower_components/*` and `node_modules/*` and then `npm install` and `bower install`)

**Comment by timbertson** [comment]
Great, thanks - it's all working locally for me now :)
