### ISSUE TITLE
After uploading images, page refreshes and closes other open grains

### ISSUE THREAD

**Issue by neynah** [mnutt/davros#5]
Not a big deal but slightly inconvenient. :)

(The images do, however, upload successfully)

**Comment by mnutt** [comment]
Can you tell me what browser version this happens on? I just fixed a bug where text is unselectable afterwards, I'd like to test if that change perhaps fixes this too.

**Comment by neynah** [comment]
I'm on chrome 46.0.2490.86. It looks like it's been fixed- I can't reproduce the issue. Awesome thanks! :)
