### ISSUE TITLE
Davros 0.17.0 broken on Edge

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#51]
Sadly nearly unusable for me, right now. :/ Menu has vanished, weird scrollbar on the side column.

![davrosonedge](https://cloud.githubusercontent.com/assets/4399499/15911373/4ac34d5e-2d95-11e6-8f00-850e7122467b.png)

**Comment by paulproteus** [comment]
What is the question-mark pointing out, out of curiosity?

**Comment by ocdtrekkie** [comment]
There is usually a menu button up there. Which is, for one, the only place you can delete a file.

**Comment by paulproteus** [comment]
Ah hah, right, thanks, I forgot.

**Comment by mnutt** [comment]
Ahh thanks for pointing these out! I'm going to try to out some automated tests in place to catch these in the future.

**Comment by paulproteus** [comment]
BTW @mnutt there is heightened interest over the past month or two in automated tests for Sandstorm apps. So if your testing framework happens to be reusable (e.g. "copy-paste these things into your .travis.yml") then that could be neat.

Having said that, these IE/Edge bugs are catchable without invoking Sandstorm at all, so you might not need it.

Also consider that Sauce Labs has free-of-cost multi-browser Selenium service for open source projects.

**Comment by ocdtrekkie** [comment]
Any word on when this might be fixed?

As a useful note, while testing if this was fixed, I drag selected the top bar, and discovered that the menu button actually IS there, and does work. It's just invisible. So it is probably mostly/"just" an icon display issue?

**Comment by mnutt** [comment]
This should be fixed now in 0.18. The webfont-based icon set needed some extra css.

**Comment by ocdtrekkie** [comment]
Looks good to me.
