### ISSUE TITLE
Davros not really working in v0.170

### ISSUE THREAD

**Issue by germakoci** [mnutt/davros#55]
Since the weekend update of Sandstorm, we can't really use Davros anymore; it stays hanging, uploads functions some times, sometimes they don't; then the whole thing is starting to function great for a while and then back to hanging.

**Comment by mnutt** [comment]
It's likely an issue with some sandstorm changes that need to be reflected in the sandstorm-http-bridge compiled into davros. I'm building a new version right now, sorry about that.

**Comment by germakoci** [comment]
@mnutt is there going to be an automatic update or the new version should be uploaded manually ?

**Comment by mnutt** [comment]
It's approved and in the app marketplace. When you load sandstorm, there should be a red notification in the top right. Click that, and you can automatically upgrade your grains.

**Comment by mnutt** [comment]
This should be fixed. Can you let me know if you're still seeing issues?

**Comment by germakoci** [comment]
@mnutt thanks a lot, works great, checked with other having access to it, all seem to work just fine
