### ISSUE TITLE
Support for Nextcloud clients?

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#56]
Worth asking, and if so, noting in docs. Does Davros work with Nextcloud's Android or iOS clients? As Nextcloud has a lot of the previous development force behind ownCloud, Davros will probably want to maintain compatibility with their clients as well.

**Comment by mnutt** [comment]
I definitely plan on it, but haven't looked into if there are any differences to account for. It looks like the Nextcloud iOS app is a whole new app so will probably need some testing.

**Comment by mnutt** [comment]
I verified it works fine (in fact, better) with Nextcloud's iOS client, and will add that to the docs. I believe Nextcloud Android uses the original Owncloud Android codebase and so should work fine, but haven't tested.
