### ISSUE TITLE
Issues with Set up your own domain or subdomain

### ISSUE THREAD

**Issue by iRGBit** [mnutt/davros#59]
I'm trying to set up my own domain within Davros on Sandstorm Oasis
but the DNS records don't show up when I enter my domain name - tested on Mac in Firefox 47.0 and Chrome 51.0.2704

**Comment by mnutt** [comment]
Hello, I believe I've fixed this with the latest update. (v0.21.5) Would you mind trying it now?

**Comment by mnutt** [comment]
I'm going to close this for now because I'm pretty sure it was fixed, but please comment here if you're still seeing it after upgrading and I will re-open.
