### ISSUE TITLE
No progress bar during upload (MS Edge, 1607 build)

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#60]
I'm not seeing any sort of progress bar or indicator when uploading a file. Just seeing the size of my grain gradually crawl upwards until the file appears in the file list.

**Comment by mnutt** [comment]
I'm hoping this was fixed by v0.21.x series, as it was present in other browsers but now is not. Please let me know if you're still seeing it in latest.

**Comment by ocdtrekkie** [comment]
Confirmed, this seems good.
