### ISSUE TITLE
Startup `history.pushState()` should be `history.replaceState()`

### ISSUE THREAD

**Issue by kentonv** [mnutt/davros#61]
Steps to reproduce:

1. Open or create a Davros grain.
2. Click "back" in the browser.

**Expected result:** Goes back to grain list.

**Actual result:** Goes back to "loading" animation in Davros and then immediately forward again. Repeated clicks simply repeat this sequence.

**Comments:** There is a `window.history.pushState()` occurring shortly after initial page load that ought to be a `replaceState()` instead.

**Comment by mnutt** [comment]
I've run into this before, thanks for flagging it. When you visit `/` it redirects to `/files/` for consistency, but it ends up breaking the back button. `replaceState()` should make the back button work as expected.

**Comment by mnutt** [comment]
Fixed with https://github.com/mnutt/davros/commit/1252d43b710983f30e61bca5df39b35b1cdd7436.
