### ISSUE TITLE
PDF View Bug

### ISSUE THREAD

**Issue by marceldostal** [mnutt/davros#63]
Height of `<div class="file file-pdf">` is always 252px when opening an PDF. 
Testet with Firefox, Chrome and Edge.
Occurred after the last update (21.08.2016)

![pdfview](https://cloud.githubusercontent.com/assets/19998459/17855862/1e0fbf6a-687b-11e6-965f-a76b2d137278.JPG)

**Comment by mnutt** [comment]
This is the same issue as seen in https://github.com/mnutt/davros/issues/62 and should be fixed in v0.21.6 which should be generally available now. Please re-open if you are still seeing it after the upgrade.
