### ISSUE TITLE
Cannot clone repository on Windows

### ISSUE THREAD

**Issue by Geemili** [mnutt/davros#64]
It gives this error:

```
Cloning into 'davros'...
remote: Counting objects: 267, done.
remote: Compressing objects: 100% (220/220), done.
remote: Total 267 (delta 13), reused 164 (delta 4), pack-reused 0
Receiving objects: 100% (267/267), 2.70 MiB | 17.00 KiB/s, done.
Resolving deltas: 100% (13/13), done.
Checking connectivity... done.
fatal: cannot create directory at '24:24:^:': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

A search on google brings up [this issue](https://github.com/swcarpentry/DEPRECATED-bc/issues/463), which is similar. Essentially, they were having issues because the folder name 'aux' was reserved for some reason. The issue here is that the folder '24:24:^:' contains the `^` character, which isn't allowed in a folder name on Windows.

Is it possible to rename the folder?

**Comment by mnutt** [comment]
Sorry about that! That directory should have never been checked in in the first place. It gets created as a cache for thumbnails, and should have been created in a .gitignored directory in my local checkout.

Additionally, https://github.com/mnutt/davros/commit/0b860ea7413b46cb2cc059b156264166e1cec5e1 updates davros to use windows-friendly filenames for its thumbnail caches.

**Comment by Geemili** [comment]
Thanks for the fast response! Cloning works just fine now. :)
