### ISSUE TITLE
web publishing doesn't quite work

### ISSUE THREAD

**Issue by jadeqwang** [mnutt/davros#7]
Does Davros do something different from Hacker CMS and/or Ghost?

![image](https://cloud.githubusercontent.com/assets/1584904/11010395/4dbeb6ac-8493-11e5-947f-e1f7c7ff1d83.png)

**Comment by ocdtrekkie** [comment]
Did you add an index.html file, as it says?

**Comment by jadeqwang** [comment]
Doh.

**Comment by mnutt** [comment]
I think I can probably detect if you're missing `/index.html` and warn you about it. Maybe there are use cases where you don't want to put something at `/` but I can't think of one.

**Comment by jadeqwang** [comment]
Actually, maybe include a blank index.html at creation?

**Comment by jadeqwang** [comment]
I'm super excited that this is now my new home for Skitches. :)

**Comment by mnutt** [comment]
That's a good idea. Maybe, if you don't have an index.html, automatically create one with "Edit or replace this file in the root of your shared directory".
