### ISSUE TITLE
Is it possible to change which drive Davros stores files in on my Sandstorm server?

### ISSUE THREAD

**Issue by TheDavidJohnson** [mnutt/davros#80]
This is a fantastic project. Love it.

Unfortunately, I didn't think too much about where the files would end up and uploaded too many gigantic files to my server. I have 2 drives in the server: one for the OS and applications, and one for "data." 

Naturally, the Sandstorm / Davros setup is running on my OS drive, and apparently that's where the files are being stored. I uploaded one too many huge files and everything ground to a halt.

I'd like to move the files from the OS drive to my much larger data store. Is this possible?

Thanks!

**Comment by TheDavidJohnson** [comment]
As a follow-up, after commenting here I continued searching and located [this comment](https://groups.google.com/d/msg/sandstorm-dev/TLpGZpF6HJw/W70SMKHaAQAJ) in a Google Groups thread.

It reads:

> I would suggest a bind-mount over a symlink. However, you really don't need to do either. Sandstorm doesn't hardcode the directory /opt/sandstorm -- if you move the whole thing to a new location, it will still work.
> 
> You will need to fix up a couple things:
> - /etc/init.d/sandstorm or /etc/systemd/system/sandstorm.service (depending on your init system) will need to be modified to point at the new path (assuming you want Sandstorm to start at boot).
> - The `sandstorm` and `spk` symlinks in /usr/local/bin will need to be updated to the new location (if you care about these commands still being in your PATH).

I'm going to give this a try on my Debian box and see how it works. Will report back. In the meantime, if there's a more current or better method for this, I'd love to know! Thanks!

**Comment by biennino** [comment]
Hi @TheDavidJohnson , I was wondering if you were able to make this work.  Could you perhaps point me in the right direction?  I'm not quite there yet, but I might run out of space soon if this keeps up. Thanks!

**Comment by ocdtrekkie** [comment]
This really isn't a Davros issue, it's a question about how Sandstorm manages storage and how to move Sandstorm storage to another drive location.

**Comment by mnutt** [comment]
Agreed, I think it probably makes the most sense to move the entire sandstorm install (/opt/sandstorm) to the new disk, or mount the disk somewhere, move sandstorm there, then remount the new disk at `/opt/sandstorm`. Unfortunately I'm pretty sure there wouldn't be any way to move Davros only to a new disk.
