### ISSUE TITLE
Davros outdated in sandstrom appstore?? 

### ISSUE THREAD

**Issue by sunrayfan** [mnutt/davros#85]
Hi

Version 0.21.7 (sandstrom app store) is far behind github. Is this the reason why **BUGS** like the one described in **issue #69** with  **File deletion** are not addressed?

Best,
Jörg

**Comment by ocdtrekkie** [comment]
The primary difference, as far as I know, is that 0.23 has added LibreOffice binaries for document previews. But it'd probably be good to get an update on this.

**Comment by ocdtrekkie** [comment]
Davros is no longer outdated on the Sandstorm App Market! https://apps.sandstorm.io/app/8aspz4sfjnp8u89000mh2v1xrdyx97ytn8hq71mdzv4p4d8n0n3h

However, ownCloud/Nextcloud clients are not currently supported in Davros.
