### ISSUE TITLE
Error when using ember serve about jsDAV in v0.13.1

### ISSUE THREAD

**Issue by kerwan** [mnutt/davros#86]
Hi I downloaded the latest release (v0.13.1),
while running "PORT=3009 ember serve" I had the following error about including jsDAV:
`Cannot find module 'jsdav/lib/DAV/plugin'`

In the following files :  
- server/dav/notify.js 
- server/dav/root-delete.js 

The lines including jsDAV have a typo, they use `jsdav/lib/DAV/plugin` instead of `jsDAV/lib/DAV/plugin`
I think you have corrected it in the master branch but maybe this can be mentionned in the release comment ?

Thank for this great app by the way !

**Comment by mnutt** [comment]
Hi @kerwan, at some point I stopped updating the Github Releases. I'll push a new release version soon. Thanks for letting me know.

**Comment by kerwan** [comment]
Thanks for this quick reply.
So can I consider using the master branch instead ? Is it stable for now ?

**Comment by mnutt** [comment]
To close this out: I’m pushing git tags again; feel free to use the latest tag or to directly use `master` since I do work in development branches and try to always ensure that `master` is functional.
