### ISSUE TITLE
Double scrollbars on PDF preview in Firefox

### ISSUE THREAD

**Issue by ocdtrekkie** [mnutt/davros#92]
When viewing a PDF file on Firefox 59, the preview embed is larger than the page, and hence, the Davros frame has a scrollbar, and then the PDF embed, also containing a PDF that does not fit in the embed, has it's own scrollbar. You can end up having to adjust the outer scrollbar to be able to reach the bottom of the inner scrollbar.

**Comment by mnutt** [comment]
I believe this is fixed now, but please let me know if it is not.

**Comment by ocdtrekkie** [comment]
Yeah, this looks good to me too.
