### ISSUE TITLE
Newest OwnCloud Linux desktop client says Davros server type no longer supported

### ISSUE THREAD

**Issue by xet7** [mnutt/davros#93]
Hi,
today I updated OwnCloud Linux desktop client on my Xubuntu 16.04 64bit, and it says Davros server type is no longer supported, so it does not work anymore.

**Comment by Clint76** [comment]
Facing the same issue connecting to my Sandstorm Davros grain on Ubuntu 16.04 LTS with ownCloud windows client after client updated to 2.5.0

**Comment by alessandropaglierani** [comment]
Same issue here!

**Comment by andreasseiler** [comment]
Same issue, a fix would be highly appreciated!

**Comment by FelixFurtmayr** [comment]
Same issue for me.

**Comment by frigginglorious** [comment]
Does anyone know if someone is going to fork this and update DAVROS to fix this bug.

DO WE HAVE A HERO?!

**Comment by ocdtrekkie** [comment]
I was hoping my comment here might spark some love: https://news.ycombinator.com/item?id=19250319

:(

**Comment by xet7** [comment]
Well, there is already info here why this is broken https://github.com/owncloud/client/issues/6775#issuecomment-422423147 but it needs someone that has time to fix it.
