### ISSUE TITLE
Davros responds with unexpected gzipped response

### ISSUE THREAD

**Issue by timmc** [mnutt/davros#94]
When I make a request to Davros's WebDAV endpoint with curl or a browser, I get garbage back. It turns out that there are possibly two separate problems here.

- With curl, the request does not have an `Accept-Encoding` header, but the response has `Content-Encoding: gzip`
- With Firefox, the request has `Accept-Encoding: gzip, deflate, br`, but there is no `Content-Encoding` response header.

However, in both cases gzipped data is returned, and the client is confused. (In another client, there's no trouble, but it might be cueing off the response headers alone.)

This may or may not be related to https://github.com/sandstorm-io/sandstorm/issues/2691

**Comment by mnutt** [comment]
Based on the discussion in https://github.com/sandstorm-io/sandstorm/issues/2691, this looks like it was fixed there. Feel free to reopen if that is not the case.

**Comment by ocdtrekkie** [comment]
I think I just hit this or something very related when troubleshooting a 403 Forbidden response from an app I'm working on, re: request in Firefox had the Accept-Encoding, but the response did not have a Content-Encoding header.
